# Paths
path=(
  /usr/local/opt/coreutils/libexec/gnubin
  $DOTFILES/bin
  /usr/local/bin
  /usr/{sbin,bin}
  /{sbin,bin}
)

cdpath=(
  $HOME
  $HOME/code
  $HOME/Downloads
)

fpath=(
  /usr/local/share/zsh-completions
  $fpath
)

manpath=(
  /usr/local/opt/coreutils/libexec/gnuman
)

# Ensure path arrays do not contain duplicates.
typeset -gU path cdpath fpath manpath

# load rbenv if available
if command -v rbenv >/dev/null; then
  eval "$(rbenv init - --no-rehash)"
fi

# vim: ft=zsh sw=2 ts=2 et
