# use nvim as the visual editor
export VISUAL=nvim
export EDITOR=$VISUAL

# Dotfiles location
export DOTFILES=$HOME/repos/dotfiles

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# load rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init - --no-rehash)"

# Must be sourced at the end of this file.
source ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
