# Load plugins
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/share/zsh-history-substring-search/zsh-history-substring-search.zsh

# Load configuration files
for file ($DOTFILES/zsh/config/*.zsh(N)); do
  source $file
done

# Load modules files
for file ($DOTFILES/zsh/modules/*.zsh(N)); do
  source $file
done

unset file

[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
[[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh
