# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Prompt based on the Solarized Dark theme.
# Use 14pt Monaco for Powerline with 1.1 vertical space.
ZSH_THEME="rap"

ZSH_CUSTOM=$HOME/.dotfiles/zsh

plugins=(
  bundler
  colored-man-pages
  gitfast
  history-substring-search
  zsh-syntax-highlighting              # must be the last plugin in the array
)

source $ZSH/oh-my-zsh.sh

# Load configuration files
for zsh_source in $HOME/code/dotfiles/zsh/config/*.zsh; do
  source $zsh_source
done

# If zshrc.local exists, load it.
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

[[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh

# load nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
